### ISSUE TITLE
Error when using the driver

### ISSUE THREAD

**Issue by OskarBrink** [clandmeter/com.qubino.shutter#1]
Based on your input related to other github reported issue ([https://github.com/athombv/homey/issues/2140]) I worked with fvanbeenen to test the shutter module with your driver, realising you indicated some errors to be expected.
 
We are getting the following error code at the moment we are trying to activate commands (the inclusion went okay):

com.qubino.shutter running...
TypeError: Cannot read property 'CommandClass' of undefined
    at optionsCapability.forEach.optionsCapabilityItem (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:123:15)
    at Array.forEach (<anonymous>)
    at ZwaveDriver.capabilities.(anonymous function).set (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:99:23)
    at /manager/drivers.js:1:3626
    at ZwaveDriver.fs.existsSync.drivers.(anonymous function).ready (/manager/drivers.js:1:2266)
    at clientDriverMessage (/manager/drivers.js:1:2949)
    at Homey.ready (/manager/drivers.js:1:446)
    at Object.Homey.ready (/homey.js:1:1073)
    at /manager/drivers.js:1:400
    at /helpers/client.js:1:1040
    at Array.forEach (<anonymous>)
    at process.<anonymous> (/helpers/client.js:1:1009)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

--- INFO: com.qubino.shutter has been killed ---

**Comment by willumpie82** [comment]
I have the same issue, pairing went okay but same error as @OskarBrink when trying to controlling the device

Homey FW: 1.5.3 (latest stable)

p.s. I added the ZMNHCDx AC230v shutter myself, (just copy-paste and modify the descriptors)

**Comment by plsth** [comment]
Same here..   
Firmware 1.5.8


C:\Users\Patrik\Desktop\com.qubino.shutter-master>athom app run
┌────────────────────────────────────────────┐
│ Hey developer, we're hiring! View our open │
│ positions at https://go.athom.com/jobs     │
└────────────────────────────────────────────┘
✓ Validating app...
✓ Homey App validated successfully against level `debug`
✓ Packing Homey App...
✓ Installing Homey App on `Homey` (http://192.168.1.219:80)...
✓ Homey App `com.qubino.shutter` successfully installed
✓ Running `com.qubino.shutter`, press CTRL+C to quit
─────────────── Logging stdout & stderr ───────────────
com.qubino.shutter running...
TypeError: Cannot read property 'CommandClass' of undefined
    at optionsCapability.forEach.optionsCapabilityItem (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:123:15)
    at Array.forEach (<anonymous>)
    at ZwaveDriver.capabilities.(anonymous function).set (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:99:23)
    at /manager/drivers.js:1:3626
    at ZwaveDriver.fs.existsSync.drivers.(anonymous function).ready (/manager/drivers.js:1:2266)
    at clientDriverMessage (/manager/drivers.js:1:2949)
    at Homey.ready (/manager/drivers.js:1:446)
    at Object.Homey.ready (/homey.js:1:1073)
    at /manager/drivers.js:1:400
    at /helpers/client.js:1:1040
    at Array.forEach (<anonymous>)
    at process.<anonymous> (/helpers/client.js:1:1009)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

--- INFO: com.qubino.shutter has been killed ---

**Comment by plsth** [comment]
Stack trace:

TypeError: Cannot read property 'CommandClass' of undefined
at optionsCapability.forEach.optionsCapabilityItem (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:123:15)
at Array.forEach (<anonymous>)
at ZwaveDriver.capabilities.(anonymous function).set (/node_modules/homey-zwavedriver/lib/ZwaveDriver.js:99:23)
at /manager/drivers.js:1:3626
at ZwaveDriver.fs.existsSync.drivers.(anonymous function).ready (/manager/drivers.js:1:2266)
at clientDriverMessage (/manager/drivers.js:1:2949)
at Homey.ready (/manager/drivers.js:1:446)
at Object.Homey.ready (/homey.js:1:1073)
at /manager/drivers.js:1:400
at /helpers/client.js:1:1040
at Array.forEach (<anonymous>)
at process.<anonymous> (/helpers/client.js:1:1009)
at emitTwo (events.js:126:13)
at process.emit (events.js:214:7)
at emit (internal/child_process.js:772:12)
at _combinedTickCallback (internal/process/next_tick.js:141:11)
at process._tickCallback (internal/process/next_tick.js:180:9)

Exit code: 1
Exit signal: null
